version: "3.4"

services:
  docsmedia:
    image: docsmedia
    container_name: soda_docs-media
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
